version: 2

common_steps: &common_steps
  - checkout
  - run:
      name: Prepare environment
      command: |
        apt-get update
        apt-get install -y --no-install-recommends libssl-dev
        bundle install
  - run:
      name: Test
      command: bundle exec rake test

jobs:
  ruby255:
    docker:
      - image: ruby:2.5.5
    steps: *common_steps

workflows:
  version: 2
  build:
    jobs:
      - ruby255
