name: Test
on:
  - push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Install Ruby
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.5

    - name: Run tests
      id: run-tests
      run: |
        bundle install
        bundle exec rake test
